[tool.poetry]
name = "leetcode-solutions"
version = "0.1.0"
description = ""
authors = ["Heber F Barra <heberferreirabarra@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
